import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { preparationApi } from '../api/preparation.api.js';
import { BinBlock } from '../components/domain.jsx';
import { EmptyState, ErrorState, LoadingState, RefreshButton, StatusBadge } from '../components/common.jsx';
import { UnitVisual, ViewModeToggle } from '../components/visual-layout.jsx';
import { useRefreshableData } from '../hooks/useRefreshableData.js';
import { normalizeVisualUnit } from '../utils/visual-layout.js';
import { QuickSetup } from '../components/QuickSetup.jsx';

function ConfirmAction({ label, message, onConfirm, danger = true, disabled = false }) {
  const [confirming, setConfirming] = useState(false);
  if (!confirming) return <button type="button" className={`button ${danger ? 'button-danger' : 'button-secondary'}`} disabled={disabled} onClick={() => setConfirming(true)}>{label}</button>;
  return <div className="inline-confirm"><span>{message}</span><button type="button" className="button button-secondary" onClick={() => setConfirming(false)}>Cancel</button><button type="button" className={`button ${danger ? 'button-danger' : 'button-primary'}`} onClick={() => { setConfirming(false); onConfirm(); }}>Confirm</button></div>;
}

function GenerateBinsForm({ label, onGenerate, disabled, hasExistingBins = false }) {
  const [count, setCount] = useState(1);
  return <form className="compact-form" onSubmit={(e) => { e.preventDefault(); onGenerate(Number(count)); }}><label>{label}<input type="number" min="1" max="10000" step="1" value={count} onChange={(e) => setCount(e.target.value)} /></label><button className="button button-primary" disabled={disabled}>{hasExistingBins ? 'Add Bins' : 'Generate Bins'}</button><p className="field-help">{hasExistingBins ? 'New permanent Bins continue after the highest existing Bin number. Existing Bins are unchanged.' : 'Permanent Bin IDs and sequential codes are generated by the backend.'}</p></form>;
}

function SideForm({ existingTypes, side, onSave, onCancel, disabled }) {
  const [sideType, setSideType] = useState(side?.sideType || ['FRONT', 'RIGHT', 'BACK', 'LEFT'].find((type) => !existingTypes.includes(type)) || 'FRONT');
  const [displayOrder, setDisplayOrder] = useState(side?.displayOrder || 0);
  return <form className="compact-form horizontal" onSubmit={(e) => { e.preventDefault(); onSave({ sideType, displayOrder: Number(displayOrder), ...(side ? { version: side.version } : {}) }); }}><label>Side<select value={sideType} onChange={(e) => setSideType(e.target.value)}>{['FRONT', 'RIGHT', 'BACK', 'LEFT'].map((type) => <option key={type} value={type} disabled={existingTypes.includes(type) && type !== side?.sideType}>{type}</option>)}</select></label><label>Order<input type="number" min="0" value={displayOrder} onChange={(e) => setDisplayOrder(e.target.value)} /></label><div className="form-actions gap"><button type="button" className="button button-secondary" onClick={onCancel}>Cancel</button><button className="button button-primary" disabled={disabled}>Save Side</button></div></form>;
}

function BayForm({ bay, onSave, onCancel, disabled }) {
  const [number, setNumber] = useState(bay?.bayNumber || 1);
  const [order, setOrder] = useState(bay?.displayOrder || 0);
  return <form className="compact-form horizontal" onSubmit={(e) => { e.preventDefault(); onSave({ bayNumber: Number(number), displayOrder: Number(order), ...(bay ? { version: bay.version } : {}) }); }}><label>Bay number<input type="number" min="1" value={number} onChange={(e) => setNumber(e.target.value)} /></label><label>Display order<input type="number" min="0" value={order} onChange={(e) => setOrder(e.target.value)} /></label><div className="form-actions gap"><button type="button" className="button button-secondary" onClick={onCancel}>Cancel</button><button className="button button-primary" disabled={disabled}>Save Bay</button></div></form>;
}

function ShelfForm({ shelf, bays, onSave, onCancel, disabled, forcedScope }) {
  const [scope, setScope] = useState(forcedScope || shelf?.shelfScope || 'BAY');
  const [bayId, setBayId] = useState(shelf?.bayId || bays[0]?.id || '');
  const [number, setNumber] = useState(shelf?.shelfNumber || 1);
  const [order, setOrder] = useState(shelf?.displayOrder || 0);
  const submit = (e) => {
    e.preventDefault();
    const payload = { shelfScope: scope, shelfNumber: Number(number), displayOrder: Number(order), ...(shelf ? { version: shelf.version } : {}) };
    if (scope === 'BAY') payload.bayId = bayId;
    onSave(payload);
  };
  return <form className="compact-form shelf-form" onSubmit={submit}>{forcedScope ? <div><span className="eyebrow">Scope</span><strong>Standalone (SH)</strong></div> : <label>Scope<select value={scope} onChange={(e) => setScope(e.target.value)}><option value="BAY" disabled={!bays.length}>Bay shelf</option><option value="STANDALONE">Standalone (SH)</option></select></label>}{scope === 'BAY' && <label>Bay<select value={bayId} required onChange={(e) => setBayId(e.target.value)}>{bays.map((bay) => <option key={bay.id} value={bay.id}>{bay.code}</option>)}</select></label>}<label>Shelf number<input type="number" min="1" value={number} onChange={(e) => setNumber(e.target.value)} /></label><label>Display order<input type="number" min="0" value={order} onChange={(e) => setOrder(e.target.value)} /></label><div className="form-actions gap"><button type="button" className="button button-secondary" onClick={onCancel}>Cancel</button><button className="button button-primary" disabled={disabled || (scope === 'BAY' && !bayId)}>Save Shelf</button></div></form>;
}

function ShelfMapping({ shelf, bins, onSave, saving }) {
  const [editing, setEditing] = useState(false);
  const [selected, setSelected] = useState(() => new Set(shelf.binMappings.map((mapping) => mapping.binId)));
  useEffect(() => setSelected(new Set(shelf.binMappings.map((mapping) => mapping.binId))), [shelf]);
  if (!editing) return <button className="button button-secondary" type="button" onClick={() => setEditing(true)}>Manage Bins ({shelf.binMappings.length})</button>;
  const toggle = (id) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  return <div className="mapping-editor"><p className="field-help">Bins already mapped to another Shelf are unavailable.</p><div className="bin-check-grid">{bins.map((bin) => { const elsewhere = bin.assignedShelfId && bin.assignedShelfId !== shelf.id; return <label className={elsewhere ? 'disabled' : ''} key={bin.id}><input type="checkbox" checked={selected.has(bin.id)} disabled={elsewhere} onChange={() => toggle(bin.id)} /><span>{bin.code}</span></label>; })}</div><div className="form-actions gap"><button className="button button-secondary" type="button" onClick={() => setEditing(false)}>Cancel</button><button className="button button-primary" type="button" disabled={saving} onClick={() => { onSave([...selected]); setEditing(false); }}>Save mapping</button></div></div>;
}

function ShelfCard({ shelf, bins, bays, onMutate, saving, mutable = true }) {
  const [editing, setEditing] = useState(false);
  return <article className="structure-card"><div className="card-title-row"><div><p className="eyebrow">{shelf.shelfScope === 'STANDALONE' ? 'Standalone' : 'Bay shelf'}</p><h4>{shelf.structuralCode || shelf.code}</h4></div><span>{shelf.binMappings.length} Bins</span></div>{mutable && (editing ? <ShelfForm shelf={shelf} bays={bays} disabled={saving} onCancel={() => setEditing(false)} onSave={(payload) => { onMutate(() => preparationApi.updateShelf(shelf.id, payload)); setEditing(false); }} /> : <div className="card-actions"><ShelfMapping shelf={shelf} bins={bins} saving={saving} onSave={(ids) => onMutate(() => preparationApi.assignShelfBins(shelf.id, ids), 'Shelf mapping saved.')} /><button className="button button-secondary" onClick={() => setEditing(true)}>Edit</button><ConfirmAction label="Delete" message="Delete this empty Shelf?" onConfirm={() => onMutate(() => preparationApi.deleteShelf(shelf.id))} disabled={saving || shelf.binMappings.length > 0} /></div>)}</article>;
}

function BayCard({ bay, sideBins, allBays, onMutate, saving, mutable }) {
  const [editing, setEditing] = useState(false);
  const [addingShelf, setAddingShelf] = useState(false);
  const shelves = [...bay.shelves].sort((a, b) => a.shelfNumber - b.shelfNumber);
  return <article className="bay-card"><div className="card-title-row"><div><p className="eyebrow">Bay</p><h3>{bay.code}</h3></div><span>{shelves.length} Shelves</span></div>{mutable && editing && <BayForm bay={bay} disabled={saving} onCancel={() => setEditing(false)} onSave={(payload) => { onMutate(() => preparationApi.updateBay(bay.id, payload)); setEditing(false); }} />}{mutable && <div className="card-actions"><button className="button button-secondary" onClick={() => setAddingShelf(true)}>Add Shelf</button><button className="button button-secondary" onClick={() => setEditing(true)}>Edit Bay</button><ConfirmAction label="Delete Bay" message="Delete this empty Bay?" disabled={saving || shelves.length > 0} onConfirm={() => onMutate(() => preparationApi.deleteBay(bay.id))} /></div>}{mutable && addingShelf && <ShelfForm bays={[bay]} disabled={saving} onCancel={() => setAddingShelf(false)} onSave={(payload) => { onMutate(() => preparationApi.createShelf(bay.sideId, payload)); setAddingShelf(false); }} />}<div className="shelf-stack">{shelves.map((shelf) => <ShelfCard key={shelf.id} shelf={shelf} bins={sideBins} bays={allBays} onMutate={onMutate} saving={saving} mutable={mutable} />)}</div></article>;
}

function PreparationBins({ bins, mutable, onDelete, saving }) {
  return <div className="preparation-bin-grid">{bins.map((bin) => <div className="preparation-bin" key={bin.id}><BinBlock bin={bin} />{mutable && <ConfirmAction label="Remove" message={`Delete ${bin.code}?`} disabled={saving || Boolean(bin.assignedShelfId)} onConfirm={() => onDelete(bin.id)} />}</div>)}</div>;
}

function PreparationRouteMap({ data, mutable, onAddSide, onNavigate }) {
  const scrollTo = (id) => { onNavigate(); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); };
  const summary = data.summary;
  if (data.unitType === 'BASKET') {
    const steps = [
      { number: 1, label: 'Generate Bins', status: summary.binCount ? `${summary.binCount} Bins` : 'Start here', target: 'basket-bins', enabled: true },
      { number: 2, label: 'Review', status: summary.binCount ? 'Available' : 'Generate Bins first', target: 'review', enabled: summary.binCount > 0 },
      { number: 3, label: 'Finalize', status: mutable ? (summary.binCount ? 'Ready for review' : 'Pending') : 'Complete', target: 'review', enabled: summary.binCount > 0 }
    ];
    return <section className="card preparation-route-map"><div><p className="eyebrow">Basket Preparation</p><h2>Preparation Progress</h2><p>Generate permanent Bins, review them, then explicitly finalize the Unit.</p></div><ol className="basket-steps">{steps.map((step) => <li key={step.number} className={!mutable && step.number === 3 ? 'complete' : ''}><button type="button" disabled={!step.enabled} onClick={() => scrollTo(step.target)}><span>{step.number}</span><strong>{step.label}</strong><small>{step.status}</small></button></li>)}</ol></section>;
  }

  const hasSides = summary.sideCount > 0;
  const hasBins = summary.binCount > 0;
  const hasShelves = summary.shelfCount > 0;
  const mapped = hasBins && summary.unassignedBinCount === 0;
  const steps = [
    { number: 1, label: 'Side Setup', status: hasSides ? `${summary.sideCount} configured` : 'Add at least one Side', target: 'rack-sides', enabled: true },
    { number: 2, label: 'Bin Setup', status: hasBins ? `${summary.binCount} Bins` : hasSides ? 'Generate Bins next' : 'Create a Side first', target: 'rack-sides', enabled: hasSides },
    { number: 3, label: 'Bay / Shelf Setup', status: hasShelves ? `${summary.shelfCount} Shelves` : hasSides ? 'Bay, standalone, or both' : 'Create a Side first', target: 'rack-structure', enabled: hasSides },
    { number: 4, label: 'Bin Mapping', status: hasBins ? (hasShelves ? `${summary.assignedBinCount} / ${summary.binCount} mapped` : 'Create a Shelf first') : 'Generate Bins first', target: 'rack-mapping', enabled: hasBins && hasShelves },
    { number: 5, label: 'Review', status: mapped && hasShelves ? 'Ready' : 'Incomplete', target: 'review', enabled: true },
    { number: 6, label: 'Finalize', status: mutable ? (mapped && hasShelves ? 'Ready to Finalize' : 'Pending') : 'Complete', target: 'review', enabled: true }
  ];
  return <section className="card preparation-route-map"><div className="route-map-heading"><div><p className="eyebrow">Rack Preparation</p><h2>Preparation Progress</h2><p>Sides → Bins → Bays/Shelves → Mapping → Review → explicit Finalize</p></div>{mutable && !hasSides && <button type="button" className="button button-primary" onClick={onAddSide}>+ Add Side</button>}</div><ol>{steps.map((step) => <li key={step.number} className={step.number < 5 && ((step.number === 1 && hasSides) || (step.number === 2 && hasBins) || (step.number === 3 && hasShelves) || (step.number === 4 && mapped)) ? 'complete' : ''}><button type="button" disabled={!step.enabled} onClick={() => step.target && scrollTo(step.target)}><span>{step.number}</span><strong>{step.label}</strong><small>{step.status}</small></button></li>)}</ol><div className="side-readiness" aria-label="Configured Rack sides">{['FRONT', 'RIGHT', 'BACK', 'LEFT'].map((type) => <span key={type} className={data.sides.some((side) => side.sideType === type) ? 'configured' : ''}>{type} {data.sides.some((side) => side.sideType === type) ? '✓' : '—'}</span>)}</div></section>;
}

function ReviewSection({ data, mutable, saving, onFinalize }) {
  const [showDetails, setShowDetails] = useState(false);
  const summary = data.summary;
  const ready = data.unitType === 'BASKET'
    ? summary.binCount > 0
    : summary.sideCount > 0 && summary.shelfCount > 0 && summary.binCount > 0 && summary.unassignedBinCount === 0;
  return <section id="review" className="preparation-review scroll-target"><h2>{data.unit.code}</h2><strong className="review-bin-count">{summary.binCount} Bins</strong><span className={ready ? 'ready-text' : 'text-error'}>{ready ? 'Ready' : 'Not ready'}</span>{showDetails && <dl className="review-details">{data.unitType === 'RACK' && <><div><dt>Sides</dt><dd>{summary.sideCount}</dd></div><div><dt>Bays</dt><dd>{summary.bayCount}</dd></div><div><dt>Shelves</dt><dd>{summary.shelfCount}</dd></div><div><dt>Unmapped</dt><dd>{summary.unassignedBinCount}</dd></div></>}</dl>}<button className="button button-secondary" onClick={() => setShowDetails((value) => !value)}>{showDetails ? 'Hide Details' : 'View Details'}</button>{mutable ? <ConfirmAction label="Lock & Start" danger={false} disabled={saving || !ready} message={`Lock ${data.unit.code}? You cannot change its setup after this.`} onConfirm={onFinalize} /> : <strong className="done-state">✓ Started</strong>}</section>;
}

function RackSide({ side, allTypes, mutable, onMutate, saving }) {
  const [expanded, setExpanded] = useState(true);
  const [mode, setMode] = useState(null);
  const allShelves = [...side.bays.flatMap((bay) => bay.shelves), ...side.standaloneShelves].sort((a, b) => a.shelfNumber - b.shelfNumber);
  return <section className="card side-section"><button className="side-heading" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded}><div><p className="eyebrow">Rack side</p><h2>{side.sideType} <span className="muted">({side.code})</span></h2></div><div className="side-counts"><span>{side.bins.length} Bins</span><span>{side.bays.length} Bays</span><span>{allShelves.length} Shelves</span><strong>{expanded ? '−' : '+'}</strong></div></button>{expanded && <div className="side-body">
    {mutable && <div className="toolbar compact"><button className="button button-secondary" onClick={() => setMode('editSide')}>Edit Side</button><button className="button button-secondary" onClick={() => setMode('bay')}>Add Bay</button><button className="button button-secondary" onClick={() => setMode('shelf')}>Add Standalone Shelf</button><ConfirmAction label="Delete Side" message="Delete this empty Side?" disabled={saving || side.bins.length > 0 || side.bays.length > 0 || allShelves.length > 0} onConfirm={() => onMutate(() => preparationApi.deleteSide(side.id))} /></div>}
    {mode === 'editSide' && <SideForm side={side} existingTypes={allTypes} disabled={saving} onCancel={() => setMode(null)} onSave={(payload) => { onMutate(() => preparationApi.updateSide(side.id, payload)); setMode(null); }} />}
    {mode === 'bay' && <BayForm disabled={saving} onCancel={() => setMode(null)} onSave={(payload) => { onMutate(() => preparationApi.createBay(side.id, payload)); setMode(null); }} />}
    {mode === 'shelf' && <ShelfForm bays={side.bays} forcedScope="STANDALONE" disabled={saving} onCancel={() => setMode(null)} onSave={(payload) => { const standalone = { ...payload, shelfScope: 'STANDALONE' }; delete standalone.bayId; onMutate(() => preparationApi.createShelf(side.id, standalone)); setMode(null); }} />}
    <div className="subsection-heading"><div><h3>Physical Bins</h3><p>{side.bins.length ? 'Assign each Bin to one Shelf before finalization.' : 'Generate the permanent Bin sequence once.'}</p></div></div>
    {mutable && <GenerateBinsForm label={side.bins.length ? 'Additional Bins' : 'Number of Bins'} hasExistingBins={side.bins.length > 0} disabled={saving} onGenerate={(count) => onMutate(() => preparationApi.generateSideBins(side.id, count), `${count} Bins added.`)} />}
    {side.bins.length > 0 && <PreparationBins bins={side.bins} mutable={mutable} saving={saving} onDelete={(id) => onMutate(() => preparationApi.deleteBin(id))} />}
    <div className="subsection-heading"><h3>Bays and Shelves</h3></div><div className="bay-grid">{side.bays.map((bay) => <BayCard key={bay.id} bay={bay} sideBins={side.bins} allBays={side.bays} onMutate={onMutate} saving={saving} mutable={mutable} />)}</div>
    {!!side.standaloneShelves.length && <div className="standalone-section"><h3>Standalone Shelves</h3><div className="shelf-stack">{[...side.standaloneShelves].sort((a, b) => a.shelfNumber - b.shelfNumber).map((shelf) => <ShelfCard key={shelf.id} shelf={shelf} bins={side.bins} bays={side.bays} onMutate={onMutate} saving={saving} mutable={mutable} />)}</div></div>}
  </div>}</section>;
}

export function UnitPreparationPage() {
  const { unitId } = useParams();
  const view = useRefreshableData(() => preparationApi.getPreparation(unitId), [unitId]);
  const [addingSide, setAddingSide] = useState(false);
  const [saving, setSaving] = useState(false);
  const [mutationError, setMutationError] = useState(null);
  const [message, setMessage] = useState(null);
  const [viewMode, setViewMode] = useState('simple');
  const [previewBin, setPreviewBin] = useState(null);
  const [setupMode, setSetupMode] = useState('quick');
  const data = view.data;
  const mutable = data?.unit.status === 'PREPARATION';
  const sides = useMemo(() => data?.sides || [], [data]);

  const mutate = async (work, success = 'Structure updated.') => {
    setSaving(true); setMutationError(null); setMessage(null);
    try { await work(); await view.refresh(); setMessage(success); }
    catch (error) { setMutationError(error); if (error.code === 'STALE_VERSION' || error.code === 'UNIT_STRUCTURE_LOCKED') await view.refresh().catch(() => {}); }
    finally { setSaving(false); }
  };
  const finalize = () => mutate(() => preparationApi.finalizeUnit(unitId), 'Stock Take started. This structure is now locked.');

  return <>
    <Link className="back-link" to={data?.unit.zoneId ? `/preparation/zones/${data.unit.zoneId}` : '/preparation'}>← Preparation</Link>
    <div className="page-heading minimal-heading"><div><h1>{data?.unit.name || data?.unit.code || 'Setup'}</h1>{data && <span>{data.unit.code}</span>}</div><RefreshButton onClick={() => view.refresh().catch(() => {})} refreshing={view.refreshing} /></div>
    {view.loading && <LoadingState />}
    {view.error && !data && <ErrorState error={view.error} onRetry={() => view.refresh().catch(() => {})} />}
    {view.error && data && <div className="alert alert-warning">Refresh failed. Showing the last successful structure.</div>}
    {message && <div className="alert alert-info">{message}</div>}
    {mutationError && <div className="alert alert-error" role="alert"><div><strong>{mutationError.message}</strong>{Array.isArray(mutationError.details) && <ul>{mutationError.details.map((detail, index) => <li key={`${mutationError.code}-${index}`}>{typeof detail === 'string' ? detail : detail.message || JSON.stringify(detail)}</li>)}</ul>}</div></div>}
    {data && setupMode === 'quick' && <QuickSetup data={data} refresh={view.refresh} onAdvanced={() => setSetupMode('advanced')} />}
    {data && setupMode === 'advanced' && <><div className="toolbar"><button className="button button-secondary" onClick={() => setSetupMode('quick')}>← Quick Setup</button></div><PreparationRouteMap data={data} mutable={mutable} onNavigate={() => setViewMode('simple')} onAddSide={() => { setViewMode('simple'); setAddingSide(true); }} /></>}
    {data && setupMode === 'advanced' && <div className="dashboard-view-row"><ViewModeToggle value={viewMode} onChange={setViewMode} /><span>{viewMode === 'visual' ? 'Read-only structural preview' : 'Advanced editing controls'}</span></div>}
    {previewBin && <div className="alert alert-info"><div><strong>{previewBin.code}</strong><p>{previewBin.stockStatus} · {previewBin.stockItemCount || 0} stock items</p></div><button className="button button-secondary" onClick={() => setPreviewBin(null)}>Close</button></div>}
    {data && setupMode === 'advanced' && <div hidden={viewMode !== 'visual'}><UnitVisual model={normalizeVisualUnit(data)} progress={data.progress} onBinSelect={setPreviewBin} /></div>}
    {data?.unitType === 'RACK' && setupMode === 'advanced' && <div id="rack-sides" className="scroll-target" hidden={viewMode !== 'simple'}>
      {mutable && <div className="toolbar"><button className="button button-primary" disabled={sides.length >= 4} onClick={() => setAddingSide(true)}>Add Side</button></div>}
      {addingSide && <section className="card form-panel"><SideForm existingTypes={sides.map((side) => side.sideType)} disabled={saving} onCancel={() => setAddingSide(false)} onSave={(payload) => { mutate(() => preparationApi.createSide(unitId, payload)); setAddingSide(false); }} /></section>}
      {!sides.length && <EmptyState title="No structure configured yet">Start by adding at least one Side. A Rack may use one to four of FRONT, RIGHT, BACK, and LEFT.</EmptyState>}
      {!!sides.length && !data.summary.binCount && <div className="alert alert-info"><strong>{sides.map((side) => side.sideType).join(', ')} created.</strong><span> Next: Generate physical Bins for the appropriate Side.</span></div>}
      <div id="rack-structure" className="stack scroll-target">{sides.map((side) => <RackSide key={side.id} side={side} allTypes={sides.map((item) => item.sideType)} mutable={mutable} onMutate={mutate} saving={saving} />)}</div>
      {!!data.summary.binCount && <section id="rack-mapping" className="card mapping-overview scroll-target"><div><p className="eyebrow">Shelf-Bin Mapping</p><h2>Map Bins</h2><p>Open a Shelf’s “Manage Bins” control above. Bays are optional: standalone Shelves and mixed structures are supported.</p></div><div className="mapping-counts"><span>Total <strong>{data.summary.binCount}</strong></span><span>Mapped <strong>{data.summary.assignedBinCount}</strong></span><span>Unmapped <strong>{data.summary.unassignedBinCount}</strong></span></div></section>}
    </div>}
    {data?.unitType === 'BASKET' && setupMode === 'advanced' && <div hidden={viewMode !== 'simple'}><section id="basket-bins" className="card basket-preparation scroll-target"><div className="section-heading"><div><p className="eyebrow">Direct structure</p><h2>Basket Bins</h2><p>{data.summary.binCount} permanent Bins. Baskets do not use Sides, Bays, Shelves, or mapping.</p></div><StatusBadge value={data.unit.status} /></div>{mutable && <GenerateBinsForm label={data.bins.length ? 'Additional Bins' : 'Number of Bins'} hasExistingBins={data.bins.length > 0} disabled={saving} onGenerate={(count) => mutate(() => preparationApi.generateBasketBins(unitId, count), `${count} Basket Bins added.`)} />}{data.bins.length ? <PreparationBins bins={data.bins} mutable={mutable} saving={saving} onDelete={(id) => mutate(() => preparationApi.deleteBin(id))} /> : <EmptyState title="No Basket Bins">Generate at least one direct Bin, then review and explicitly finalize.</EmptyState>}</section></div>}
    {data && (data.summary.binCount > 0 || !mutable) && (setupMode === 'quick' || viewMode === 'simple') && <ReviewSection data={data} mutable={mutable} saving={saving} onFinalize={finalize} />}
  </>;
}
